### ISSUE TITLE
Contribuir com o projeto

### ISSUE THREAD

**Issue by brunopulis** [saiadecasa/saiadecasa.github.io#104]
Como faço para contribuir?

**Comment by jackmakiyama** [comment]
@brunopulis basta forkar adicionar o evento ou feature e fazer uma PR junto com a motivação. Acho que isso já é suficiente para o pessoal debater o assunto da PR... =D

**Comment by rogeriopradoj** [comment]
@jackmakiyama , acho que é o momento de criarmos um `CONTRIBUTING.md`!

- Regra do GitHub: https://github.com/blog/1184-contributing-guidelines
- Exemplo/modelo: https://github.com/jden/CONTRIBUTING.md

**Comment by jackmakiyama** [comment]
Opa, com certeza @rogeriopradoj .
Assim que eu tiver um tempo eu posso escrever um rascunho e fazer uma PR pra irmos refinando, claro se alguém não tiver um modelo pronto hahahaha.

**Comment by brunopulis** [comment]
@jackmakiyama Eu até vi que vocês mudaram a estrutura para inclusão de eventos com um arquivos JSON, mas não consegui achar ele quando dei um fork do projeto, talvez por noobice minha mesmo :p

**Comment by jackmakiyama** [comment]
A sim, mas o json é apenas metadata, [esse arquivo](https://github.com/saiadecasa/saiadecasa.github.io/blob/master/javascripts/events.js) que mantem os eventos.

**Comment by brunopulis** [comment]
@jackmakiyama  Resolvido o problema aqui dei um fork novamente aqui! Valeu :+1:

**Comment by rogeriopradoj** [comment]
@brunopulis, criado o CONTRIBUTING.md.

Acho que é o começo para mostrar para o pessoal onde achar as contribuições, certo?

Fechando a issue!
