### ISSUE TITLE
Pedir a localização do usuário, e dizer a distância daquele evento

### ISSUE THREAD

**Issue by rogeriopradoj** [saiadecasa/saiadecasa.github.io#106]
Ideia de, com base no endereço cadastrado do evento, e da localização do usuário, ter essa distância como um item.

Ou talvez um intervalo/range!

Sugestão:

- até 2km
- até 5km
- até 10km
- até 25km
- até 50km
- até 100km
- mais de 100km

@saiadecasa/collaborators o que acham?

**Comment by rogeriopradoj** [comment]
Ah, a ideia do range vem do http://www.meetup.com/find/

**Comment by IAMFELIPESOUZA** [comment]
Fala @rogeriopradoj 
cara acho uma puta ideia, podemos até utilizar a API geolocation do HTML5 para dar get no user.

Eu estava pensando em criar um app do saiadecasa no titanum mesmo, dai já mata nas plataformas IOS e Android, podemos até implementar a ideia da localização no mesmo.
O processo de incerção de eventos pode continuar o mesmo, via PR, e podemos fazer um sync do PR do evento com o webservice para atualizar os eventos no app.

o que acha?

**Comment by rogeriopradoj** [comment]
@IAMFELIPESOUZA, não acho muito legal a ideia de aplicativos nativos não... Para mim, no máximo, um webapp seria o suficiente.

No PHPSP + Pub de Abril conversei com o @rafaell-lycan, o que ele sugeriu o mais rápido para essa situação de fazer funcionar melhor em dispositivos móveis é fazer o layout responsivo.

**Comment by rogeriopradoj** [comment]
@IAMFELIPESOUZA agora, sobre a geolocalização, a ideia seria usar o HTML5 mesmo!

**Comment by giorgiofellipe** [comment]
Desculpem pela intromissão, a ideia é realmente bacana.

No caso de desenvolver o app híbrido eu particularmente aconselho o [Ionic](http://ionicframework.com/), trabalha totalmente com AngularJS e permite utilizar quaisquer uma das extensões do [ngCordova](http://ngcordova.com/), simples e rápido de desenvolver.

De qualquer forma me disponho a auxiliar no desenvolvimento!

**Comment by rogeriopradoj** [comment]
A contribuição #233 resolveu essa issue! \o/
