### ISSUE TITLE
Repetição de evento

### ISSUE THREAD

**Issue by jackmakiyama** [saiadecasa/saiadecasa.github.io#107]
Olá galera, 
Pensei em um esquema de repetição de evento, aproveitando que agora é tudo por Js o cadastro.

Exemplo de repetição é o PHPSP+Pub que tem sempre no mesmo local e na segunda quinta do mês.

Não listaria o evento mais de uma vez, só mostraria a segunda data assim que a primeira passar ou em uma opção de eventos futuros.

O que acham?

**Comment by abbondanza** [comment]
Ola @jackmakiyama .. acho isso uma boa idea. Talvez isso possa nos ajudar: http://bunkat.github.io/later/

**Comment by williamespindola** [comment]
Pode ser legal, mas também tira a interação. O formato de input dos events ser via PR é uma maneira as pessoas interagirem e também para aquela cara que esta começando aprender como se faz um PR em um projeto.

**Comment by jackmakiyama** [comment]
@williamespindola acho um ponto valido o que levantou, mas também ficamos sem registro desses eventos muitas das vezes que acontecem exatamente por não cadastrarem, e eventos fixos são uma grande minoria comparamdo com os eventos que acontecem com data marcada aleatoriamente.

**Comment by jackmakiyama** [comment]
@abbondanza  boa, =D...

Vamos desenrolar e analizar a viabilidade... =D

**Comment by rogeriopradoj** [comment]
Pessoal, também acredito que complica um pouco a interação, como o @williamespindola citou.

Nos meetups/plugins de eventos/facebooks, na minha visão, já é complicado colocar esses eventos com repetição, pois depende de alguém ficar responsável por ver se isso está tudo certo nos eventos seguintes, tudo baseado em uma chave só: a primeira inclusão.

Eu sugiro que não façamos essa inclusão no saiadecasa. Se tem eventos repetidos, é chato, mas façamos a inclusão do evento quantas vezes ele se repetir.

E quando o evento tiver passado a data, é só ir lá e excluir os eventos passados.

Meu voto para essa sugestão: :-1:

**Comment by jackmakiyama** [comment]
@rogeriopradoj :+1: 

Então acho que essa issue pode ser fechada.
Obrigado... o/

**Comment by jackmakiyama** [comment]
@rogeriopradoj :+1: 

Então acho que essa issue pode ser fechada.
Obrigado... o/

**Comment by rogeriopradoj** [comment]
Valeu, @jackmakiyama !
