### ISSUE TITLE
LazyLoading Google Maps

### ISSUE THREAD

**Issue by gpedro** [saiadecasa/saiadecasa.github.io#113]
opa,

eu acho realmente desnecessário abrir todos as localizações como mapas dinâmicos do Gmaps.

![benchmarking osx - chrome - 2015-05-11](https://cloud.githubusercontent.com/assets/2898638/7559220/28c77270-f781-11e4-8f0d-493481b32e2d.png)

e isso pesa e dá uma travada no carregamento da página. é muita coisa D:

Fiz um LazyLoading onde você clica na imagem mapa (que é um [staticmap](https://developers.google.com/maps/documentation/staticmaps/?hl=pt-br#quick_example)) e ele carrega o mapa dinâmico.
![captura de tela 2015-05-11 as 01 55 58](https://cloud.githubusercontent.com/assets/2898638/7559241/65e44b92-f781-11e4-9254-ed51f5c396de.png)

**Comment by gpedro** [comment]
bem melhor :metal:

**Comment by giorgiofellipe** [comment]
Boa! :thumbsup:
