### ISSUE TITLE
Um novo estilo para o site

### ISSUE THREAD

**Issue by andersonweb** [saiadecasa/saiadecasa.github.io#135]
Com o crescimento do projeto, poderíamos fazer um novo layout, talvez usar até um static generator como Jekyll ou Hexo. O que acha da ideias amigos ? 
@IAMFELIPEMATTOS @rogeriopradoj @williamespindola

**Comment by rogeriopradoj** [comment]
https://github.com/saiadecasa/saiadecasa.github.io/issues/59
