### ISSUE TITLE
Filtro por estado e/ou cidade

### ISSUE THREAD

**Issue by renanmpimentel** [saiadecasa/saiadecasa.github.io#154]
Pessoal,

O que acham de criarmos um filtro por estado e/ou cidade ? 
Acredito que isso ia ajudar bastante na experiencia do usuário.

**Comment by rafaell-lycan** [comment]
Por estado eu concordo plenamente =)

2015-08-31 9:16 GMT-03:00 Renan Martins Pimentel <notifications@github.com>:

> Pessoal,
>
> O que acham de criarmos um filtro por estado e/ou cidade ?
> Acredito que isso ia ajudar bastante na experiencia do usuário.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saiadecasa/saiadecasa.github.io/issues/154>.
>



-- 

*Rafael Almeida*Web Designer & Developer

*(11) 9.8819.3240 - 9.8657.2173*www.rafaell-lycan.com

**Comment by IAMFELIPEMATTOS** [comment]
show @renanmpimentel acho uma ótima ideia, vamos trabalhar melhor nisso.
xá só eu dar um grito nos owners para avaliarmos a ideia.

cc: @rogeriopradoj @williamespindola

**Comment by rogeriopradoj** [comment]
Acho muito bom! Acredito que possa ter ligação com esse aqui: https://github.com/saiadecasa/saiadecasa.github.io/issues/106

**Comment by renanmpimentel** [comment]
@rogeriopradoj é, eu tinha visto issue #106 antes de abrir está.. as duas vão se complementar de forma bem agradavel para o usuário..

Vou ver se essa semana inicio então!

**Comment by rogeriopradoj** [comment]
Blz!

**Comment by williamespindola** [comment]
@renanmpimentel  Desde o início não colocamos filtro porque a idéia era manter simples a interface do site. Tivemos a idéia da geolocalização #106 pois desta forma o filtro é instantâneo.

**Comment by renanmpimentel** [comment]
Vamos atacar a #106 :+1:

**Comment by williamespindola** [comment]
ok!
