### ISSUE TITLE
Usar Platform.sh para, a cada Pull Request, gerar URL temporária para revisão

### ISSUE THREAD

**Issue by rogeriopradoj** [saiadecasa/saiadecasa.github.io#156]
Lendo o artigo http://symfony.com/blog/how-we-auto-deploy-documentation-pull-requests-with-platform-sh do Projeto Symfony achei a ideia muito bacana.

Eles estão usando esse formato para, a cada Pull Request recebido no repositório do GitHub, ser gerada uma URL com o conteúdo dessa contribuição já compilada!

Será que conseguimos colocar esse processo para rodar?

**Comment by rogeriopradoj** [comment]
Infelizmente o custo seria muito alto para mantermos essa opção: https://platform.sh/pricing/.

Mandei um tweet para eles, vamos ver se temos alguma ajuda: https://twitter.com/rogeriopradoj/status/648677327258447872

**Comment by IAMFELIPEMATTOS** [comment]
@rogeriopradoj o plano Development atende?

**Comment by rogeriopradoj** [comment]
Oi, @IAMFELIPEMATTOS , talvez, mas ainda assim é muito caro esses 10 USD por mês.

**Comment by IAMFELIPEMATTOS** [comment]
@rogeriopradoj os caras deram algum retorno?

**Comment by rogeriopradoj** [comment]
Olá, @IAMFELIPEMATTOS , em parte.

Já mandamos o e-mail que eles pediram, agora é esperar um pouco mais:

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/platformsh">@platformsh</a> I loved <a href="http://t.co/bqrmtT8OXT">http://t.co/bqrmtT8OXT</a>. If we have an OSS project, could we have your support? <a href="https://t.co/6BemN22Nb6">https://t.co/6BemN22Nb6</a> cc <a href="https://twitter.com/w_espindola">@w_espindola</a></p>&mdash; Rogerio Prado J (@rogeriopradoj) <a href="https://twitter.com/rogeriopradoj/status/648677327258447872">September 29, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/rogeriopradoj">@rogeriopradoj</a> <a href="https://twitter.com/w_espindola">@w_espindola</a> contact me - robert@platform.sh</p>&mdash; Platform.sh (@platformsh) <a href="https://twitter.com/platformsh/status/649287643151364096">September 30, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/platformsh">@platformsh</a> sent, Robert! Thanks for taking a look. cc <a href="https://twitter.com/w_espindola">@w_espindola</a> <a href="https://twitter.com/SaiaDeCasaDev">@saiadecasadev</a></p>&mdash; Rogerio Prado J (@rogeriopradoj) <a href="https://twitter.com/rogeriopradoj/status/649593604265127936">October 1, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
