### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by gjuniioor** [saiadecasa/saiadecasa.github.io#165]
Gostaria de sugerir a adição de uma favicon.

Procurei por "Get out" e achei umas que gostei:

- [1](https://www.iconfinder.com/icons/282258/checkout_get_out_go_out_late_check-out_logout_night_life_sign_out_icon)
- [2](https://www.iconfinder.com/icons/27856/exit_out_sign_out_icon)

Encontrei algumas imagens mais cômicas e que curti mais:

- [1](http://marketingmasteryelite.com/blog/wp-content/uploads/2015/08/getout.jpg)
- [2](http://financialcryptography.com/images/get-out-of-jail2.gif)
- [3](http://rlv.zcache.com/gtfo_get_out_guy_rage_face_comic_meme_poster-re92252d92fe5492496d2d7844054a058_jih_8byvr_324.jpg)

Coloquei aqui como issue por conta de uma possível votação.

É isso, vamos decidir o melhor aí. Qualquer coisa, só mudar da imagem do pull request que fiz.

**Comment by IAMFELIPEMATTOS** [comment]
cc: @rogeriopradoj @williamespindola

**Comment by williamespindola** [comment]
Pessoalmente não gostei de nenhum. Quais vocês gostaram?
Estes desenhos necessariamente o desenho precisa remeter a sair de casa ou pela porta. Mas pode ter a ver com código, programar.

**Comment by gjuniioor** [comment]
Então, a imagem é o foco da discussão. Sou péssimo para essas coisas... Meu gosto não bate com o de ninguém kkkk

Sugere outros, pls.

**Comment by rogeriopradoj** [comment]
Acho legal ter um favicon também, mas nenhuma dessas opções agradou.

Com base no comentário do @williamespindola https://github.com/saiadecasa/saiadecasa.github.io/issues/165#issuecomment-146062412, será que temos algum designer para criar realmente um logo/favicon?

**Comment by gjuniioor** [comment]
Exatamente, @rogeriopradoj , seria a melhor solução.

Como não tenho tino pra coisa, o jeito foi arrumar umas opções por ai.

**Comment by gjuniioor** [comment]
cc: @IAMFELIPEMATTOS @williamespindola @rogeriopradoj 

Será que ainda tem futuro ou melhor deixar como está e fechar essa issue mesmo?

**Comment by Diego-Soares** [comment]
Acho que pode ser uma coisa simples! Vou deixar a minha sugestão:

![home](https://cloud.githubusercontent.com/assets/5099569/15696556/ecae27b0-2787-11e6-9f4f-d5b9bf819fc3.png)

**Comment by williamespindola** [comment]
Opa vamos ver se conseguimos fechar esta issue hehehe
A primeira opção do @gjuniioor agradou, mas falta algo relacionado a programação
A opção do @Diego-Soares é lega, mas não referencia a saída nem código.
Bom ja que o programador esta saindo de casa para falar sobre código vamos colocar algo que lembre isto:

![image](https://cdn4.iconfinder.com/data/icons/developer-set-3/128/code-128.png)
