### ISSUE TITLE
Evento semanal

### ISSUE THREAD

**Issue by jackmakiyama** [saiadecasa/saiadecasa.github.io#205]
Olá pessoal, aqui em Sinop-MT temo  o #HoraExtra semanalmente, saiadecasa também recebe eventos assim?

**Comment by hussani** [comment]
Acho que recebe desde que seja colocada uma entrada para cada evento.

Pode ser relacionada com a #107.

**Comment by jackmakiyama** [comment]
@hussani verdade, então vamos seguir como disse... =D... Vou fechar essa issue.. =D

**Comment by rogeriopradoj** [comment]
@jackmakiyama , vocês estão usando Meetup para controlar os eventos? Ou é outra ferramenta?

Falou!
