### ISSUE TITLE
Filtro e/ou ordenação por distância

### ISSUE THREAD

**Issue by lucasbento** [saiadecasa/saiadecasa.github.io#249]
Seria interessante a implementação de um filtro e/ou ordenação por distância para rapidamente sabermos quais eventos seriam mais _fáceis_ de comparecer, o que acham?

**Comment by hussani** [comment]
Eu gosto bastante da ideia @lucasbsilva, mas acho que a implementação é meio complicada dependendo somente de frontend.

Acho que seria necessário um serviço backend pra conseguir processar a distância sem sofrer com performance.
Mas posso estar estupidamente enganado também.

**Comment by lucasbsilva** [comment]
@hussani não acho que seria complicado e pela demanda atual de eventos acredito que não seria algo tão pesado para o front.

Vou ver se consigo implementar algo para isso assim que tiver um tempinho.

**Comment by rogeriopradoj** [comment]
Olá, @lucasbsilva, quando tiver algo mande um Pull Request para discutirmos, ok?

**Comment by Diego-Soares** [comment]
Acho que um filtro por cidade/estado seria mais interessante, um filtro de distância, funcionaria melhor pelo celular(mobile).

**Comment by rogeriopradoj** [comment]
Blz, @Diego-Soares ! Se puder, manda um Pull Request para discutirmos, ok?

Valeu!
