### ISSUE TITLE
Como pegar coordenadas corretas?

### ISSUE THREAD

**Issue by theandersonn** [saiadecasa/saiadecasa.github.io#262]
Mudou os parâmetros das coordenadas?
Como pegar coordenadas corretas?

**Comment by IAMFELIPEMATTOS** [comment]
Opa @theandersonn, desculpe a demora cara, dei o merge pelo celular e não vi sua pergunta.

Sobre a questão das coordenadas, eu geralmente verifico a mesma de 2 formas:
 - Vejo as coordenadas que são geradas quando você acessa o mapa, o mesmo é passado na URL vou te mostrar um exemplo:
![screenshot from 2016-03-28 13 12 59](https://cloud.githubusercontent.com/assets/5552126/14082530/e34c5882-f4e6-11e5-9fac-dcdbc134e866.png)
com isso vou vendo se bate realmente com o local.
- A outra forma é acessar as coordenadas diretamente do local, clicando com o botão direito em cima do mesmo.

![screenshot from 2016-03-28 13 17 28](https://cloud.githubusercontent.com/assets/5552126/14082734/f7b35c0c-f4e7-11e5-844c-7c99cd576ca8.png)

após isso, ele gera as coordenadas >
![screenshot from 2016-03-28 13 20 31](https://cloud.githubusercontent.com/assets/5552126/14082744/0791f930-f4e8-11e5-91a2-a682f504089e.png)

mas de qualquer forma ambas soluções que eu encontrei eu verifico ponto a ponto, procuro as coordenadas mais proximas possiveis se não a exata.

se souber de outra solução, compartilhe conosco!

thx

**Comment by theandersonn** [comment]
@IAMFELIPEMATTOS Eu estava pegando através do incorporar mapa, por isso da variação.
Vou adotar esse método que vc citou. :+1:
