### ISSUE TITLE
Fix Travis CI build: https://travis-ci.org/saiadecasa/saiadecasa.github.io

### ISSUE THREAD

**Issue by rogeriopradoj** [saiadecasa/saiadecasa.github.io#298]
Olá, pessoal, atualmente o Build no Travis CI está falhando. [![Build Status](https://travis-ci.org/saiadecasa/saiadecasa.github.io.svg?branch=master)](https://travis-ci.org/saiadecasa/saiadecasa.github.io)

Não é um problema tão grave, pois o pessoal da https://platform.sh/ nos cedeu acesso a plataforma deles e todo Pull Request que o projeto recebe é renderizado no seguinte formato:

http://pr-#{NUMERO DO PR}-4opeh37pcjdwu.us.platform.sh/ (exemplo, no PR #297, a url era http://pr-297-4opeh37pcjdwu.us.platform.sh/).

Mesmo assim, é bacana que tenhamos a suíte de testes no Travis CI válida, então essa Issue está aberta para isso.

**Importante**: esperamos que a solução seja feita por novos contribuidores! Assim, incentive alguém que nunca contribuiu com o projeto para mandar a primeira contribuição, beleza? Aqui umas referências:
- https://yourfirstpr.github.io/
- http://makeapullrequest.com/

**Comment by hussani** [comment]
só novinhos?

**Comment by rogeriopradoj** [comment]
É a ideia, @hussani ! Incentiva alguém a mandar bala!

**Comment by hussani** [comment]
@minkah10

**Comment by williamespindola** [comment]
Galera vou tomar a frente desta issue ela ja esta a muito tempo aberta e nenhum contribuidor novo tomou frente.

**Comment by rogeriopradoj** [comment]
@williamespindola ninguém aí na empresa que conseguiria? Ninguém num pub que conseguiria? Ninguém que você conhece na rua, hehe, que conseguiria?

**Comment by williamespindola** [comment]
No momento não conheço nenhum novato.

**Comment by williamespindola** [comment]
@saiadecasa/collaborators o build esta quebrando por causa de um bug em uma dependência do HTMLHint ja houve um fix que esta previsto para a próxima release que faz um bom tempo ainda não foi lançada. Temo três opções:
1- esperar a próxima release e continuar com o build quebrado analisando e vendo que é apenas isto que esta quebrando e aceitar o PR;
2- Remover a dependência e e continuar sem hint de html;
3- Trocar de dependência;
#302
