### ISSUE TITLE
Build #419 was broken.

### ISSUE THREAD

**Issue by williamespindola** [saiadecasa/saiadecasa.github.io#382]
https://travis-ci.org/saiadecasa/saiadecasa.github.io/builds/239081886?utm_source=github_status&utm_medium=notification

**Comment by iamfelipemattos** [comment]
@williamespindola Think I found the problem, I'll try to fix!

**Comment by iamfelipemattos** [comment]
@williamespindola the problem already fixed on the [Pull Request](https://github.com/saiadecasa/saiadecasa.github.io/pull/383) I'll close this issue

**Comment by iamfelipemattos** [comment]
I'm sorry, reopened issue by accident
