### ISSUE TITLE
Atualização

### ISSUE THREAD

**Issue by lucalves** [saiadecasa/saiadecasa.github.io#422]
Olá, pessoal. Fiz a inclusão de um evento há 4 dias atrás, e ao verificar no site do projeto (https://saiadecasa.github.io/), não está atualizando com os eventos incluídos.

**Comment by williamespindola** [comment]
Parece ser algum problema com o build automático do github. Parece que agora ele esta forçando usar um tema do Jekyll. Vou dar uma olhada mais afundo para ver o que acontece.

**Comment by lucalves** [comment]
Parece que tudo se normalizou, @williamespindola. Qual foi a solução?

**Comment by williamespindola** [comment]
Foi algum problema ou lentidão com o build feito pelo github mesmo. Ainda esta aparecendo uma mensagem de erro no settings falando que não estamos usando o tema Jekyll mas os builds voltaram ao normal.

**Comment by airtonzanon** [comment]
Vendo que esta issue já está resolvida, irei fecha-la!
