### ISSUE TITLE
Hacktoberfest: Wordcamp São Paulo 2018

### ISSUE THREAD

**Issue by airtonzanon** [saiadecasa/saiadecasa.github.io#481]
Adicione este evento em nosso projeto. Qualquer dúvida, você pode ver em nossa página de [Contribuição](https://github.com/saiadecasa/saiadecasa.github.io/blob/master/CONTRIBUTING.md) ou perguntar nesta issue.

* Link para o evento: https://2018.saopaulo.wordcamp.org/

Dados necessários para a contribuição:

```
{
    titulo      : "como o evento vai aparecer no Saia de Casa!",
    dataInicio  : "no formato -> 2015-09-22",
    dataFim     : "no formato -> 2015-09-22",
    local       : "nome do local onde o evento acontece",
    endereco    : "endereço de onde o evento acontece, tente ser o mais completo possível",
    localizacao : { latitude: -25.2218113 , longitude: -54.3462431 },
    link        : "link da página do evento"
},
```

**Comment by airtonzanon** [comment]
Oh, I do not, but I can help you as well @jlapitan.
This project is to get people off their houses to tech conferences.

So to add some event on our project you should do this steps:
The events are listed on this file: javascripts/data/events.json.

The structure of one event is like this (I'll translate some keys to you below):

```
{
    titulo      : "This is the title how the event gonna be called on our project",
    dataInicio  : "event start date on this format -> 2015-09-22",
    dataFim     : "event end date on this format -> 2015-09-22",
    local       : "Name of the location that the event gonna be hosted",
    endereco    : "Address to this event. Try to give all the information about address.",
    //This key below is about location, but in lat and long
    localizacao : { latitude: -25.2218113 , longitude: -54.3462431 },
    link        : "website address"
},
```
We appreciate if you add events or remove events that was already done. So you can take a look at http://saiadecasa.github.io and remove from the file that I said above the object that is refereed to that event.

IDK if it helps, but let me know you need anything else.

**Comment by canoi12** [comment]
Opa, tudo tranquilo. Eu fiz a alteração, como faço o pull request? Dá permissão negada. Nunca fiz um pull request em repositório público, desculpa a pergunta idiota.

**Comment by airtonzanon** [comment]
Desculpa a demora pra responder @canoi12 

Mas é isso mesmo, é necessário fazer o fork. Qualquer dúvida pode me perguntar.
