### ISSUE TITLE
Formatação events.json

### ISSUE THREAD

**Issue by davelima** [saiadecasa/saiadecasa.github.io#537]
Trabalhando no events.json, percebi que o arquivo está bem bagunçado em questão de formatação (alguns blocos JSON de evento tem mais indentação que outros). Seguindo a dica de contribuição para grandes reescritas, estou abrindo essa issue para confirmar: é válido um PR apenas reformatando esse JSON?

Não é uma grande reescrita em termos de dados, mas o diff seria grande :thinking:

**Comment by airtonzanon** [comment]
Acho justo fazer um PR sobre a formatação do arquivo. Estava pensando em colocar algum standard no CI, o que acha?

**Comment by davelima** [comment]
@airtonzanon Melhor ainda! Vou trabalhar nisso, então :+1:

**Comment by airtonzanon** [comment]
@davelima criei uma lib para fazer essa verificação, ta meio porquinha, mas acho que vai rolar. https://github.com/codelicia/jsoncs

Ta rolando no PR #564
